services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - worday_db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      ENV: ${ENV}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      TEST_USER_IDS: ${TEST_USER_IDS}
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - '8000:3210'
    depends_on:
      - db

volumes:
  worday_db_data:
