name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    env:
      ENV: ${{ vars.ENV }}
      DOCKER_BUILD_TARGET: ${{ vars.DOCKER_BUILD_TARGET }}
      WORDAY_APP_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/worday_app:latest
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      TEST_USER_IDS: ${{ secrets.TEST_USER_IDS }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image with docker compose
        run: |
          docker compose build worday_app
          docker push $WORDAY_APP_IMAGE

  migrations:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    env:
      ENV: ${{ vars.ENV }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      WORDAY_APP_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/worday_app:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for new migrations
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: 'da3e7d3e8e8986614d67ac6428a9ad5a146084bc'
          filters: |
            migrations:
              - 'db/migrations/**'

      - name: Run migrations
        if: steps.filter.outputs.migrations == 'true'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_CERTIFICATE }}
          port: ${{ secrets.AWS_PORT }}
          envs: ENV,DB_HOST,DB_PORT,DB_USERNAME,DB_PASSWORD,DB_DATABASE,WORDAY_APP_IMAGE
          script: |
            docker pull $WORDAY_APP_IMAGE
            docker-compose run --rm worday_app npm run migration:run

  deploy:
    needs: [build, migrations]
    runs-on: ubuntu-latest
    environment: production
    env:
      ENV: ${{ vars.ENV }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      TEST_USER_IDS: ${{ secrets.TEST_USER_IDS }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      WORDAY_APP_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/worday_app:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to AWS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_CERTIFICATE }}
          port: ${{ secrets.AWS_PORT }}
          source: docker-compose.yml
          target: /home/${{ secrets.AWS_USERNAME }}

      - name: Run the app on AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_CERTIFICATE }}
          port: ${{ secrets.AWS_PORT }}
          envs: ENV,GEMINI_API_KEY,TELEGRAM_BOT_TOKEN,DB_HOST,DB_PORT,DB_USERNAME,DB_PASSWORD,DB_DATABASE,TEST_USER_IDS,SENTRY_DSN,WORDAY_APP_IMAGE
          script: |
            docker pull $WORDAY_APP_IMAGE
            docker-compose up -d --force-recreate
